/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NativewindRouteImport } from './routes/nativewind'
import { Route as IndexRouteImport } from './routes/index'

const NativewindRoute = NativewindRouteImport.update({
  id: '/nativewind',
  path: '/nativewind',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nativewind': typeof NativewindRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nativewind': typeof NativewindRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nativewind': typeof NativewindRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/nativewind'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/nativewind'
  id: '__root__' | '/' | '/nativewind'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NativewindRoute: typeof NativewindRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nativewind': {
      id: '/nativewind'
      path: '/nativewind'
      fullPath: '/nativewind'
      preLoaderRoute: typeof NativewindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NativewindRoute: NativewindRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
